### ISSUE TITLE
strange .gitignore

### ISSUE THREAD

**Issue by soumyaray** [RuuuBaih/SOA_project#2]
Hey folks, I’m curious why these are in your project’s `.gitignore`:

```
/config
*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/
```

Is that some standard stuff you found in other `.gitignore`s?  I’m also wondering if the `/xxxx` entries do anything at all as they seem to point to the root of your computer’s drive rather than the root of your project folder. Please help me understand!

**Comment by rainyjonne** [comment]
> Hey folks, I’m curious why these are in your project’s `.gitignore`:
> 
> ```
> /config
> *.gem
> *.rbc
> /.config
> /coverage/
> /InstalledFiles
> /pkg/
> /spec/reports/
> /spec/examples.txt
> /test/tmp/
> /test/version_tmp/
> /tmp/
> ```
> 
> Is that some standard stuff you found in other `.gitignore`s? I’m also wondering if the `/xxxx` entries do anything at all as they seem to point to the root of your computer’s drive rather than the root of your project folder. Please help me understand!

Hi! I think it's my fault haha... I create the .gitignore file by the GitHub suggested Ruby .gitignore file, and I didn't take a look at it at all (my bad haha)(p.s. I think you're right about the `point to the root of your computer’s drive rather than the root of your project folder`, and I'll delete those lines soon after!

**Comment by soumyaray** [comment]
Ahh, I guessed it was something like that.  Feel free to close this issue once you’ve cleaned up the `.gitignore` file :)

**Comment by rainyjonne** [comment]
Solved it!
